name: Build and Dockerize

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
    # install gradle 5.0
      - name: Install Gradle
        run: |
          sudo rm -rf /usr/bin/gradle
          wget https://services.gradle.org/distributions/gradle-4.8.1-bin.zip
          sudo mkdir /opt/gradle
          sudo unzip -d /opt/gradle gradle-4.8.1-bin.zip
          export PATH=$PATH:/opt/gradle/gradle-4.8.1/bin
          which gradle
          gradle -v
          chmod +x ./build.sh
          ./build.sh